project_id = "zwewwdqjvauissxzojgi"

[functions.send-waitlist-email]
verify_jwt = false

[functions.send-rent-reminder]
verify_jwt = true

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.approve-landlord]
verify_jwt = true

[functions.check-subscription-limits]
verify_jwt = true